modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/Baisylia/Cooks-Collection-1.21/issues"
license = "All Rights Reserved"

[[mods]]
modId = "cookscollection"
version = "${version}"
displayName = "Cook's Collection"
authors = "Developer: Baisylia | Designer: Bagels | Artist: Raspmary | Contributor cassiancc"
credits = "Developer: Baisylia | Designer: Bagels | Artist: Raspmary | Contributor cassiancc"
description = '''
A Farmer's Delight addon containing various additions.
'''
#logoFile = ""

[[dependencies.cookscollection]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cookscollection]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cookscollection]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"
